language: node_js

script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install -g gulp
  - npm i
  - cd functions && npm i
after_success:
  - gulp
  - firebase deploy --token $FIREBASE_TOKEN